apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messager-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nevrozza/lab-ipr-k8s.git
    targetRevision: HEAD
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: messager-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true