apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-users
  namespace: messager-app
spec:
  template:
    metadata:
      labels:
        workload: system
    spec:
      restartPolicy: OnFailure
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: workload
                    operator: In
                    values: ["system"]
      containers:
        - name: migrate-users
          image: ghcr.io/kukymbr/goose-docker:latest
          env:
            - name: GOOSE_DRIVER
              value: "postgres"
            - name: GOOSE_DBSTRING
              valueFrom:
                secretKeyRef:
                  name: messager-db-secret
                  key: USER_DB_DSN
            - name: GOOSE_MIGRATION_DIR
              value: "/migrations"
            - name: GOOSE_TABLE
              value: "goose_users_version"
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      volumes:
        - name: migrations
          configMap:
            name: users-migrations-cm
---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-messages
  namespace: messager-app
spec:
  template:
    metadata:
      labels:
        workload: system
    spec:
      restartPolicy: OnFailure
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: workload
                    operator: In
                    values: ["system"]
      containers:
        - name: migrate-messages
          image: ghcr.io/kukymbr/goose-docker:latest
          env:
            - name: GOOSE_DRIVER
              value: "postgres"
            - name: GOOSE_DBSTRING
              valueFrom:
                secretKeyRef:
                  name: messager-db-secret
                  key: MSG_DB_DSN
            - name: GOOSE_MIGRATION_DIR
              value: "/migrations"
            - name: GOOSE_TABLE
              value: "goose_messages_version"
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      volumes:
        - name: migrations
          configMap:
            name: messages-migrations-cm