apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: messager-app
resources:
  - namespace.yaml
  - configmap.yaml
  - migrations-cm.yaml
  - secret.yaml
  - postgres.yaml
  - minio.yaml
  - message-service.yaml
  - app-services.yaml
  - jobs.yaml
  - s3-csi.yaml