apiVersion: v1
kind: ConfigMap
metadata:
  name: users-migrations-cm
  namespace: messager-app
data:
  001_init_users.sql: |
    -- +goose Up
    CREATE TABLE IF NOT EXISTS users (
        id VARCHAR(255) PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    -- +goose Down
    DROP TABLE IF EXISTS users;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: messages-migrations-cm
  namespace: messager-app
data:
  001_init_messages.sql: |
    -- +goose Up
    CREATE TABLE IF NOT EXISTS messages (
        id VARCHAR(255) PRIMARY KEY,
        sender_id VARCHAR(255) NOT NULL,
        receiver_id VARCHAR(255) NOT NULL,
        text TEXT,
        file_id VARCHAR(255),
        file_name VARCHAR(255),
        edited BOOLEAN DEFAULT false,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS files (
        id VARCHAR(255) PRIMARY KEY,
        orig_name VARCHAR(255) NOT NULL,
        content_type VARCHAR(255) NOT NULL,
        path VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    -- +goose Down
    DROP TABLE IF EXISTS messages;
    DROP TABLE IF EXISTS files;