apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: messager-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
        workload: system
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: workload
                    operator: In
                    values: ["system"]
      containers:
        - name: minio
          image: minio/minio:latest
          command: ["/bin/sh", "-c"]
          args:
            - "mkdir -p /data/uploads && minio server /data --console-address :9001"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: accessKeyID
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: secretAccessKey
          ports:
            - containerPort: 9000
            - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: messager-app
spec:
  selector:
    app: minio
  ports:
    - name: s3
      port: 9000
      targetPort: 9000