apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: ru.yandex.s3.csi
    volumeHandle: s3-uploads-volume
    nodePublishSecretRef:
      name: s3-secret
      namespace: messager-app
    volumeAttributes:
      mounter: geesefs
      bucket: uploads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: message-uploads-pvc
  namespace: messager-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: s3-pv
  storageClassName: ""