apiVersion: v1
kind: Secret
metadata:
  name: messager-db-secret
  namespace: messager-app
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  USER_DB_DSN: "host=postgres user=postgres password=password dbname=messager_users sslmode=disable"
  MSG_DB_DSN: "host=postgres user=postgres password=password dbname=messager_messages sslmode=disable"
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: messager-app
type: Opaque
stringData:
  accessKeyID: "minioadmin"
  secretAccessKey: "minioadmin"
  endpoint: "http://minio.messager-app.svc.cluster.local:9000"
  region: "us-east-1"